import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google'; // Import Work Sans font
import './globals.css';

const workSans = Work_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={workSans.className}>{children}</body> {/* Use Work Sans font */}
    </html>
  );
}
